package az.ideanest;

import static org.assertj.core.api.Assertions.assertThat;

import az.ideanest.support.AbstractIntegrationTest;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.TestRestTemplate;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.SerializationFeature;
import tools.jackson.databind.json.JsonMapper;

/**
 * The published contract, exported and checked — #136.
 *
 * <p><strong>The specification is a reviewed file, not a build output nobody reads.</strong>
 * {@code apps/api/openapi.json} is generated from the running application by this test and
 * committed beside the code that produces it, and {@code @ideanest/api-client} is generated
 * from that file. The chain is what makes a breaking change visible: rename a field on a
 * response record and this test fails; accept the new specification and the client's types
 * change; a web build that still reads the old name stops compiling. Without the committed
 * copy, all three of those become an {@code undefined} on somebody's screen.
 *
 * <p>That is also why this is an assertion rather than a Gradle task that quietly rewrites
 * the file on every build. A specification regenerated by the build is a specification whose
 * changes are invisible in review, which is the same failure as accepting a visual snapshot
 * without reading it.
 *
 * <h2>Regenerating it</h2>
 *
 * <pre>{@code ./gradlew exportOpenApi}</pre>
 *
 * <p>which runs this class with {@code -Dopenapi.write=true} and overwrites the file. Read
 * the diff before committing it: every line of it is a change to something a client depends
 * on.
 *
 * <h2>Why the comparison is over parsed trees</h2>
 *
 * <p>Not over bytes. The document is built by reflecting over controllers, and while
 * {@code springdoc.writer-with-order-by-keys} makes the object keys deterministic, a
 * byte-for-byte assertion would still fail on a difference in indentation the day the
 * library changes its printer — a failure that says "the contract changed" about a contract
 * that did not. Comparing {@link JsonNode}s ignores key order and whitespace and nothing
 * else: an added field, a changed type, a removed endpoint all still fail.
 */
class OpenApiContractTests extends AbstractIntegrationTest {

    /**
     * Where the committed contract lives.
     *
     * <p>Beside {@code build.gradle.kts} rather than under {@code src/main/resources}: it is
     * not shipped inside the jar — the service generates it at runtime — and putting it on
     * the classpath would mean the deployed artefact carries a copy that can disagree with
     * the one it serves. It is at the root of the module because {@code packages/api-client}
     * reads it across the workspace, and a path into somebody's {@code src} is a path that
     * invites being moved.
     */
    private static final Path CONTRACT = Path.of("openapi.json");

    /** Set by the {@code exportOpenApi} Gradle task, and by nothing else. */
    private static final String WRITE = "openapi.write";

    /**
     * A canonical rendering, so that the committed file and the served document are compared
     * as documents and written as something a human can review.
     */
    private static final ObjectMapper CANONICAL = JsonMapper.builder()
            .enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS)
            .enable(SerializationFeature.INDENT_OUTPUT)
            .build();

    @Autowired
    private TestRestTemplate rest;

    @Test
    @DisplayName("the committed OpenAPI document is the one this service serves")
    void theContractIsCurrent() {
        JsonNode served = servedDocument();

        if (Boolean.getBoolean(WRITE)) {
            write(served);
            return;
        }

        assertThat(Files.exists(CONTRACT))
                .withFailMessage(
                        "%s is missing. Run `./gradlew exportOpenApi` and commit it: the typed clients"
                                + " in packages/api-client are generated from it.",
                        CONTRACT)
                .isTrue();

        assertThat(read())
                .withFailMessage(
                        "%s no longer describes this service. Run `./gradlew exportOpenApi`, read the"
                                + " diff — every line of it is a change some client depends on — and commit"
                                + " it with the change that caused it.",
                        CONTRACT)
                .isEqualTo(served);
    }

    /**
     * The contract is reachable without a token, because a build has none.
     *
     * <p>Asserted rather than assumed: the rule is one line in
     * {@code SecurityConfiguration}, the service denies by default, and the symptom of
     * losing it is a client generator that fetches a 401 body and produces an empty API.
     */
    @Test
    @DisplayName("the contract is published, not gated")
    void theContractIsPublished() {
        ResponseEntity<String> response = rest.getForEntity("/v3/api-docs", String.class);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).contains("\"openapi\"");
    }

    /**
     * The two conventions §10.3 states, present in the document a client is generated from.
     *
     * <p><strong>Money as a string is the one that costs real money to get wrong.</strong> If
     * the schema ever describes {@code amount} as a number, every generated client parses
     * pledges into IEEE 754 doubles and the platform starts losing qapik — silently, and in
     * the direction nobody notices until a reconciliation. The check is cheap and the failure
     * it prevents is not.
     */
    @Test
    @DisplayName("money is described as a string, and the security scheme is declared")
    void theConventionsSurviveIntoTheDocument() {
        JsonNode document = servedDocument();

        JsonNode money = document.path("components").path("schemas").path("Money");
        assertThat(money.isMissingNode())
                .withFailMessage("The document has no Money schema, so no client can be generated with one")
                .isFalse();
        assertThat(money.path("properties").path("amount").path("type").asString())
                .as("§10.3: money crosses the wire as a string, never a number")
                .isEqualTo("string");

        assertThat(document
                        .path("components")
                        .path("securitySchemes")
                        .path("bearerAuth")
                        .path("scheme")
                        .asString())
                .isEqualTo("bearer");
    }

    private JsonNode servedDocument() {
        String body = rest.getForObject("/v3/api-docs", String.class);
        return CANONICAL.readTree(body);
    }

    private static JsonNode read() {
        try {
            return CANONICAL.readTree(Files.readString(CONTRACT, StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new UncheckedIOException("Could not read " + CONTRACT.toAbsolutePath(), e);
        }
    }

    /** Writes the document with a trailing newline, because every other file in the tree has one. */
    private static void write(JsonNode document) {
        try {
            Files.writeString(
                    CONTRACT,
                    CANONICAL.writeValueAsString(document) + System.lineSeparator(),
                    StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("Could not write " + CONTRACT.toAbsolutePath(), e);
        }
    }
}
